export default interface CluesProps {
  id: number;
  submit_time: string;
  user: string;
  clue11: string;
  clue12: string;
  clue13: string;
  clue14: string;
  connection1: string;
  explanation1: string;
  clue21: string;
  clue22: string;
  clue23: string;
  clue24: string;
  connection2: string;
  explanation2: string;
  clue31: string;
  clue32: string;
  clue33: string;
  clue34: string;
  connection3: string;
  explanation3: string;
  clue41: string;
  clue42: string;
  clue43: string;
  clue44: string;
  connection4: string;
  explanation4: string;
}
